### PR TITLE
Switch to native adaptive serialization

### LINKED ISSUE #4: Adopt native adaptive serialization for query results
Adaptive output is a more flexible default for query results shown in Atom than XML output.

See similar issue raised in eXide at https://github.com/wolfgangmm/eXide/issues/167.

### PR DESCRIPTION
**Pull request by joewiz**
- Closes #4.
- Depends on https://github.com/eXist-db/exist/pull/1448. Once merged, will require eXist 3.3.0-SNAPSHOT.

### CODE REVIEW

**Comment by joewiz** [comment]
@wolfgangmm As with https://github.com/wolfgangmm/eXide/issues/168, I think this is ready to go. It would require 3.3.0-SNAPSHOT or higher, but I would assume most/all users of this package are on the cutting edge of eXist. If you're concerned about users of older versions of eXist, I'd be happy to add a check for the system version and fall back on XML serialization if so.

**Comment by wolfgangmm** [comment]
I know not all users are on a eXist develop version, so having a fallback would be great.

**Comment by joewiz** [comment]
Okay, I've got something in the works. I need to do some more testing of semver comparison, and will commit it when it's ready.

**Comment by joewiz** [comment]
Still a work in progress, but I've got what I think is a pretty robust semver checker: https://gist.github.com/joewiz/b349e2853a17bf817e5d0013d01fa9f9. 

It doesn't yet apply eXist-specific semver rules (there are a couple of such eXist-specific rules specified in https://github.com/eXist-db/exist/blob/develop/exist-versioning-release.md), but I need to see which of these are significant for the purposes of determining compatibility of features.

**Comment by duncdrum** [comment]
@joewiz how are things with this, looks like the holdups have long been superseded?

**Comment by joewiz** [comment]
@duncdrum Thanks! If we are ready to bump the minimum required version for this package to 3.3.0, this can be merged. If we need to provide compatibility with the current semver-min, 3.0.4 (see https://github.com/eXist-db/atom-editor-support/blob/master/expath-pkg.xml#L4), then I still need to add the version checking to this app as described in https://github.com/eXist-db/atom-editor-support/pull/5#issuecomment-312717160. 

Incidentally, the gist I referenced in that comment had a reply from a guy working to create a canonical test set of data for semver implementations to use. I am going to see how well my XQuery semver implementation does with that test set. They also have posted regex (which I can't simply copy and paste because there are some things like named groups that aren't available to us in XPath/XQuery) and EBNF for semver. Having things like this to reference could really help prove my code.

**Comment by duncdrum** [comment]
well provided we make a Major version release of the library when bumping to 3.3.0 I'm ok with merging this now. But if you would like to take the semVer folk's feedback into account, and add a fallback all the better. 
Just don't let the perfect be the enemy of the good, this PR is open for 18months, and 3.0.4 has long been superseded. There is more work we need to do over at atom to the `query-results` and i d like to have these changes in the lib before i get going on that.

**Comment by joewiz** [comment]
@duncdrum @wolfgangmm The PR is updated as we discussed on the Community Call.

**Review by duncdrum — APPROVED** [review]
LGTM

**Pull request merged**
